import type { Investment } from '@/lib/types'

const DAY_MS = 1000 * 60 * 60 * 24

function toIsoDateTime(date: Date, hour = 12, minute = 0) {
  const next = new Date(date)
  next.setHours(hour, minute, 0, 0)
  return next.toISOString()
}

function daysAgo(days: number, hour = 12, minute = 0) {
  return toIsoDateTime(new Date(Date.now() - days * DAY_MS), hour, minute)
}

function buildInvestment(
  partial: Omit<Investment, 'isDeleted' | 'createdAt'> & { createdAt?: string },
): Investment {
  return {
    ...partial,
    isDeleted: false,
    createdAt: partial.createdAt ?? partial.startDate,
  }
}

export interface PreviewSnapshot {
  snapshotDate: string
  totalPrincipal: number
  totalIncomeDaily: number
  totalIncomeWeekly: number
  totalIncomeMonthly: number
  totalIncomeYearly: number
  cumulativeIncome: number
  activeInvestmentCount: number
}

export const previewInvestments: Investment[] = [
  buildInvestment({
    id: 'preview-binance-usdt-flex',
    project: 'Binance',
    name: 'USDT Flexible Earn',
    url: 'https://www.binance.com',
    type: 'interest',
    amount: 185000,
    currency: 'USD',
    description: 'Preview data for flexible treasury allocation.',
    startDate: daysAgo(43, 9, 10),
    endDate: daysAgo(163, 9, 10),
    actualDays: 43,
    remark: 'Large-cap cash parking with rolling top-ups.',
    expectedApr: 7.8,
    actualApr: 8.1,
    totalIncome: 1716.16,
    dailyIncome: 41.05,
    weeklyIncome: 287.35,
    monthlyIncome: 1248.65,
    yearlyIncome: 14983.8,
    status: 'active',
  }),
  buildInvestment({
    id: 'preview-okx-usdc-dual',
    project: 'OKX',
    name: 'USDC Shark Fin',
    url: 'https://www.okx.com',
    type: 'cedefi',
    amount: 96000,
    currency: 'USD',
    description: 'Preview dual-currency structured yield position.',
    startDate: daysAgo(27, 15, 35),
    endDate: daysAgo(63, 15, 35),
    actualDays: 27,
    remark: 'Structured product showing higher coupon and shorter duration.',
    expectedApr: 12.4,
    actualApr: 13.2,
    totalIncome: 937.81,
    dailyIncome: 34.72,
    weeklyIncome: 243.03,
    monthlyIncome: 1055.1,
    yearlyIncome: 12661.2,
    status: 'active',
  }),
  buildInvestment({
    id: 'preview-bitget-usdd-wealth',
    project: 'Bitget',
    name: 'USDD Wealth',
    url: 'https://www.bitget.com',
    type: 'interest',
    amount: 72000,
    currency: 'USD',
    description: 'Preview stable income slot with moderate ticket size.',
    startDate: daysAgo(19, 11, 20),
    endDate: daysAgo(109, 11, 20),
    actualDays: 19,
    remark: 'Used as mid-risk stablecoin sleeve.',
    expectedApr: 9.6,
    actualApr: 9.2,
    totalIncome: 344.99,
    dailyIncome: 18.15,
    weeklyIncome: 127.05,
    monthlyIncome: 551.25,
    yearlyIncome: 6615,
    status: 'active',
  }),
  buildInvestment({
    id: 'preview-pendle-usde-lp',
    project: 'Pendle',
    name: 'USDe PT Basket',
    url: 'https://www.pendle.finance',
    type: 'lp',
    amount: 128000,
    currency: 'USD',
    description: 'Preview PT/YT style basis trade with elevated APR.',
    startDate: daysAgo(34, 14, 5),
    endDate: daysAgo(56, 14, 5),
    actualDays: 34,
    remark: 'Higher-volatility allocation used to enrich preview scenarios.',
    expectedApr: 18.8,
    actualApr: 17.4,
    totalIncome: 2072.88,
    dailyIncome: 61.05,
    weeklyIncome: 427.35,
    monthlyIncome: 1856.1,
    yearlyIncome: 22273.2,
    status: 'active',
  }),
  buildInvestment({
    id: 'preview-aave-usdc-lend',
    project: 'AAVE',
    name: 'USDC Lending',
    url: 'https://app.aave.com',
    type: 'lending',
    amount: 54000,
    currency: 'USD',
    description: 'Preview on-chain lending allocation.',
    startDate: daysAgo(58, 8, 45),
    endDate: daysAgo(178, 8, 45),
    actualDays: 58,
    remark: 'Lower APR, long-running defensive sleeve.',
    expectedApr: 5.7,
    actualApr: 5.9,
    totalIncome: 506.35,
    dailyIncome: 8.73,
    weeklyIncome: 61.11,
    monthlyIncome: 265.44,
    yearlyIncome: 3185.28,
    status: 'active',
  }),
  buildInvestment({
    id: 'preview-binance-usdg-vault',
    project: 'Binance',
    name: 'USDG Launchpool',
    url: 'https://www.binance.com',
    type: 'cedefi',
    amount: 88000,
    currency: 'USD',
    description: 'Preview newer stablecoin exposure for richer charts.',
    startDate: daysAgo(11, 16, 40),
    endDate: daysAgo(41, 16, 40),
    actualDays: 11,
    remark: 'Recently added position, causing visible step-up in charts.',
    expectedApr: 14.6,
    actualApr: 15.1,
    totalIncome: 400.59,
    dailyIncome: 36.42,
    weeklyIncome: 254.94,
    monthlyIncome: 1107.3,
    yearlyIncome: 13287.6,
    status: 'active',
  }),
  buildInvestment({
    id: 'preview-okx-usdt-fixed',
    project: 'OKX',
    name: 'USDT Fixed 30D',
    url: 'https://www.okx.com',
    type: 'interest',
    amount: 64000,
    currency: 'USD',
    description: 'Preview fixed-term stablecoin product nearing maturity.',
    startDate: daysAgo(7, 10, 15),
    endDate: daysAgo(23, 10, 15),
    actualDays: 7,
    remark: 'Short-term allocation created to diversify maturities.',
    expectedApr: 11.9,
    actualApr: 11.7,
    totalIncome: 143.78,
    dailyIncome: 20.52,
    weeklyIncome: 143.64,
    monthlyIncome: 621.92,
    yearlyIncome: 7463.04,
    status: 'active',
  }),
  buildInvestment({
    id: 'preview-bitget-usdc-boost',
    project: 'Bitget',
    name: 'USDC Booster',
    url: 'https://www.bitget.com',
    type: 'interest',
    amount: 47000,
    currency: 'USD',
    description: 'Preview small-ticket position for granularity.',
    startDate: daysAgo(3, 13, 25),
    endDate: daysAgo(33, 13, 25),
    actualDays: 3,
    remark: 'Freshly opened position, useful for newest activity state.',
    expectedApr: 10.2,
    actualApr: 10.5,
    totalIncome: 40.55,
    dailyIncome: 13.52,
    weeklyIncome: 94.64,
    monthlyIncome: 409.87,
    yearlyIncome: 4918.44,
    status: 'active',
  }),
  buildInvestment({
    id: 'preview-pendle-usdc-cycle',
    project: 'Pendle',
    name: 'USDC Fixed Yield',
    url: 'https://www.pendle.finance',
    type: 'lp',
    amount: 83000,
    currency: 'USD',
    description: 'Naturally matured preview position.',
    startDate: daysAgo(96, 9, 30),
    endDate: daysAgo(18, 9, 30),
    actualDays: 78,
    remark: 'Reached scheduled maturity and settled automatically.',
    expectedApr: 13.8,
    actualApr: 14.1,
    totalIncome: 2506.85,
    dailyIncome: 32.07,
    weeklyIncome: 224.49,
    monthlyIncome: 974.23,
    yearlyIncome: 11690.76,
    status: 'ended',
  }),
  buildInvestment({
    id: 'preview-aave-usdt-safe',
    project: 'AAVE',
    name: 'USDT Safe Lend',
    url: 'https://app.aave.com',
    type: 'lending',
    amount: 61000,
    currency: 'USD',
    description: 'Naturally ended conservative lending position.',
    startDate: daysAgo(154, 12, 10),
    endDate: daysAgo(32, 12, 10),
    actualDays: 122,
    remark: 'Closed after planned rebalancing window.',
    expectedApr: 6.4,
    actualApr: 6.1,
    totalIncome: 1243.62,
    dailyIncome: 10.2,
    weeklyIncome: 71.37,
    monthlyIncome: 309.27,
    yearlyIncome: 3711.24,
    status: 'ended',
  }),
  buildInvestment({
    id: 'preview-binance-usdd-early',
    project: 'Binance',
    name: 'USDD Strategy Vault',
    url: 'https://www.binance.com',
    type: 'cedefi',
    amount: 75000,
    currency: 'USD',
    description: 'Preview early exit due to risk control.',
    startDate: daysAgo(81, 17, 0),
    endDate: daysAgo(25, 10, 40),
    actualDays: 56,
    remark: 'Early redeemed after rate compression.',
    expectedApr: 15.5,
    actualApr: 11.8,
    totalIncome: 1357.81,
    dailyIncome: 24.25,
    weeklyIncome: 169.75,
    monthlyIncome: 735.57,
    yearlyIncome: 8826.84,
    status: 'early_ended',
  }),
  buildInvestment({
    id: 'preview-okx-usdt-early',
    project: 'OKX',
    name: 'USDT Snowball',
    url: 'https://www.okx.com',
    type: 'cedefi',
    amount: 52000,
    currency: 'USD',
    description: 'Preview early exit on structured product.',
    startDate: daysAgo(63, 8, 20),
    endDate: daysAgo(14, 18, 5),
    actualDays: 49,
    remark: 'Knock-out triggered early settlement.',
    expectedApr: 16.3,
    actualApr: 13.6,
    totalIncome: 949.74,
    dailyIncome: 19.38,
    weeklyIncome: 135.66,
    monthlyIncome: 587.87,
    yearlyIncome: 7054.44,
    status: 'early_ended',
  }),
]

export const previewSnapshots: PreviewSnapshot[] = [
  {
    snapshotDate: daysAgo(10).slice(0, 10),
    totalPrincipal: 535000,
    totalIncomeDaily: 164.18,
    totalIncomeWeekly: 1149.26,
    totalIncomeMonthly: 4979.94,
    totalIncomeYearly: 59759.28,
    cumulativeIncome: 18012.44,
    activeInvestmentCount: 6,
  },
  {
    snapshotDate: daysAgo(9).slice(0, 10),
    totalPrincipal: 535000,
    totalIncomeDaily: 164.18,
    totalIncomeWeekly: 1149.26,
    totalIncomeMonthly: 4979.94,
    totalIncomeYearly: 59759.28,
    cumulativeIncome: 18176.62,
    activeInvestmentCount: 6,
  },
  {
    snapshotDate: daysAgo(8).slice(0, 10),
    totalPrincipal: 623000,
    totalIncomeDaily: 200.6,
    totalIncomeWeekly: 1404.2,
    totalIncomeMonthly: 6087.24,
    totalIncomeYearly: 73046.88,
    cumulativeIncome: 18377.22,
    activeInvestmentCount: 7,
  },
  {
    snapshotDate: daysAgo(7).slice(0, 10),
    totalPrincipal: 623000,
    totalIncomeDaily: 200.6,
    totalIncomeWeekly: 1404.2,
    totalIncomeMonthly: 6087.24,
    totalIncomeYearly: 73046.88,
    cumulativeIncome: 18577.82,
    activeInvestmentCount: 7,
  },
  {
    snapshotDate: daysAgo(6).slice(0, 10),
    totalPrincipal: 623000,
    totalIncomeDaily: 200.6,
    totalIncomeWeekly: 1404.2,
    totalIncomeMonthly: 6087.24,
    totalIncomeYearly: 73046.88,
    cumulativeIncome: 18778.42,
    activeInvestmentCount: 7,
  },
  {
    snapshotDate: daysAgo(5).slice(0, 10),
    totalPrincipal: 623000,
    totalIncomeDaily: 200.6,
    totalIncomeWeekly: 1404.2,
    totalIncomeMonthly: 6087.24,
    totalIncomeYearly: 73046.88,
    cumulativeIncome: 18979.02,
    activeInvestmentCount: 7,
  },
  {
    snapshotDate: daysAgo(4).slice(0, 10),
    totalPrincipal: 687000,
    totalIncomeDaily: 221.12,
    totalIncomeWeekly: 1547.84,
    totalIncomeMonthly: 6709.16,
    totalIncomeYearly: 80509.92,
    cumulativeIncome: 19200.14,
    activeInvestmentCount: 8,
  },
  {
    snapshotDate: daysAgo(3).slice(0, 10),
    totalPrincipal: 687000,
    totalIncomeDaily: 221.12,
    totalIncomeWeekly: 1547.84,
    totalIncomeMonthly: 6709.16,
    totalIncomeYearly: 80509.92,
    cumulativeIncome: 19421.26,
    activeInvestmentCount: 8,
  },
  {
    snapshotDate: daysAgo(2).slice(0, 10),
    totalPrincipal: 687000,
    totalIncomeDaily: 221.12,
    totalIncomeWeekly: 1547.84,
    totalIncomeMonthly: 6709.16,
    totalIncomeYearly: 80509.92,
    cumulativeIncome: 19642.38,
    activeInvestmentCount: 8,
  },
  {
    snapshotDate: daysAgo(1).slice(0, 10),
    totalPrincipal: 687000,
    totalIncomeDaily: 234.64,
    totalIncomeWeekly: 1642.48,
    totalIncomeMonthly: 7119.03,
    totalIncomeYearly: 85428.36,
    cumulativeIncome: 19877.02,
    activeInvestmentCount: 9,
  },
]
