create table if not exists users (
  id integer generated by default as identity primary key,
  email text not null unique,
  password_hash text not null,
  name text,
  role text not null default 'USER',
  status text not null default 'PENDING',
  storage_mode text not null default 'LOCAL',
  timezone text not null default 'Asia/Shanghai',
  created_at text not null,
  updated_at text not null
);

create table if not exists auth_accounts (
  id integer generated by default as identity primary key,
  user_id integer not null references users(id) on delete cascade,
  provider text not null,
  provider_account_id text not null,
  email text,
  avatar_url text,
  created_at text not null,
  updated_at text not null,
  unique (provider, provider_account_id),
  unique (user_id, provider)
);

create index if not exists auth_accounts_email_idx on auth_accounts(email);

create table if not exists email_verification_codes (
  id integer generated by default as identity primary key,
  email text not null,
  code_hash text not null,
  purpose text not null default 'REGISTER',
  expires_at text not null,
  consumed_at text,
  created_at text not null
);

create index if not exists email_verification_codes_email_purpose_idx
  on email_verification_codes(email, purpose, created_at desc);

create table if not exists investments (
  id integer generated by default as identity primary key,
  user_id integer references users(id) on delete cascade,
  project text not null,
  asset_name text not null,
  url text,
  type text not null,
  amount double precision not null default 0,
  currency text not null default 'USD',
  allocation_note text,
  apr_expected double precision,
  apr_actual double precision,
  income_total double precision,
  income_daily double precision,
  income_weekly double precision,
  income_monthly double precision,
  income_yearly double precision,
  start_time text not null,
  end_time text,
  holding_days integer,
  status text not null default 'ONGOING',
  remark text,
  is_deleted boolean not null default false,
  deleted_at text,
  deleted_by integer,
  created_at text not null,
  updated_at text not null
);

create index if not exists investments_user_status_deleted_idx
  on investments(user_id, status, is_deleted);

create table if not exists investment_daily_snapshots (
  id integer generated by default as identity primary key,
  user_id integer references users(id) on delete cascade,
  investment_id integer not null references investments(id) on delete cascade,
  snapshot_date text not null,
  principal double precision not null,
  apr_expected double precision,
  apr_actual double precision,
  income_daily double precision,
  income_weekly double precision,
  income_monthly double precision,
  income_yearly double precision,
  income_total double precision,
  status text not null,
  created_at text not null,
  unique (investment_id, snapshot_date)
);

create table if not exists portfolio_daily_snapshots (
  id integer generated by default as identity primary key,
  user_id integer references users(id) on delete cascade,
  snapshot_date text not null,
  total_principal double precision not null,
  portfolio_apr_expected double precision,
  portfolio_apr_actual double precision,
  total_income_daily double precision,
  total_income_weekly double precision,
  total_income_monthly double precision,
  total_income_yearly double precision,
  cumulative_income double precision,
  active_investment_count integer not null default 0,
  created_at text not null,
  unique (user_id, snapshot_date)
);

create table if not exists operation_logs (
  id integer generated by default as identity primary key,
  user_id integer references users(id) on delete set null,
  target_type text not null,
  target_id integer,
  action text not null,
  before_data text,
  after_data text,
  ip text,
  user_agent text,
  created_at text not null
);

create table if not exists scheduled_job_logs (
  id integer generated by default as identity primary key,
  job_name text not null,
  run_date text not null,
  status text not null,
  processed_count integer not null default 0,
  duration_ms integer,
  error_message text,
  started_at text,
  finished_at text,
  created_at text not null,
  unique (job_name, run_date)
);

create table if not exists asset_sources (
  id integer generated by default as identity primary key,
  user_id integer not null references users(id) on delete cascade,
  type text not null,
  provider text not null,
  name text not null,
  public_ref text,
  encrypted_config text,
  status text not null default 'PENDING',
  last_synced_at text,
  last_error text,
  created_at text not null,
  updated_at text not null
);

create index if not exists asset_sources_user_type_idx
  on asset_sources(user_id, type, provider);

create table if not exists asset_balances (
  id integer generated by default as identity primary key,
  user_id integer not null references users(id) on delete cascade,
  source_id integer not null references asset_sources(id) on delete cascade,
  asset_symbol text not null,
  asset_name text,
  amount double precision not null default 0,
  value_usd double precision not null default 0,
  category text not null default 'OTHER',
  raw_data text,
  updated_at text not null,
  unique (source_id, asset_symbol, category)
);

create index if not exists asset_balances_user_source_idx
  on asset_balances(user_id, source_id);

create table if not exists asset_positions (
  id integer generated by default as identity primary key,
  user_id integer not null references users(id) on delete cascade,
  source_id integer not null references asset_sources(id) on delete cascade,
  provider text not null,
  chain text,
  protocol_id text,
  protocol_name text,
  position_type text not null default 'DEFI',
  asset_value_usd double precision not null default 0,
  debt_value_usd double precision not null default 0,
  reward_value_usd double precision not null default 0,
  net_value_usd double precision not null default 0,
  raw_data text,
  updated_at text not null,
  unique (source_id, provider, chain, protocol_id, position_type)
);

create index if not exists asset_positions_user_source_idx
  on asset_positions(user_id, source_id);

create table if not exists manual_assets (
  id integer generated by default as identity primary key,
  user_id integer not null references users(id) on delete cascade,
  name text not null,
  type text not null,
  amount double precision not null default 0,
  value_usd double precision not null default 0,
  note text,
  is_deleted boolean not null default false,
  deleted_at text,
  created_at text not null,
  updated_at text not null
);

create index if not exists manual_assets_user_active_idx
  on manual_assets(user_id, is_deleted);

create table if not exists asset_snapshots (
  id integer generated by default as identity primary key,
  user_id integer not null references users(id) on delete cascade,
  snapshot_date text not null,
  total_value_usd double precision not null default 0,
  breakdown text,
  created_at text not null,
  unique (user_id, snapshot_date)
);

create index if not exists asset_snapshots_user_date_idx
  on asset_snapshots(user_id, snapshot_date);

create table if not exists asset_sync_logs (
  id integer generated by default as identity primary key,
  user_id integer references users(id) on delete cascade,
  source_id integer references asset_sources(id) on delete cascade,
  status text not null,
  balance_count integer not null default 0,
  duration_ms integer,
  error_message text,
  started_at text,
  finished_at text,
  created_at text not null
);
