import type {
  AssetBalanceRecord,
  AssetPositionRecord,
  AssetSnapshotRecord,
  AssetSourceRecord,
  AssetSummaryResponse,
  AssetSyncLogRecord,
  ManualAssetRecord,
} from "@/lib/assets/types";

const DAY_MS = 24 * 60 * 60 * 1000;

function isoDaysAgo(days: number, hour = 12) {
  const value = new Date(Date.now() - days * DAY_MS);
  value.setHours(hour, 0, 0, 0);
  return value.toISOString();
}

export const previewAssetSources: AssetSourceRecord[] = [
  {
    id: 1,
    type: "CEX",
    provider: "BINANCE",
    name: "Binance Main",
    publicRef: null,
    status: "ACTIVE",
    lastSyncedAt: isoDaysAgo(0, 10),
    lastError: null,
    createdAt: isoDaysAgo(32),
    updatedAt: isoDaysAgo(0, 10),
    balanceCount: 5,
    positionCount: 0,
    totalValueUsd: 426250,
  },
  {
    id: 2,
    type: "CEX",
    provider: "OKX",
    name: "OKX Yield",
    publicRef: null,
    status: "ACTIVE",
    lastSyncedAt: isoDaysAgo(0, 9),
    lastError: null,
    createdAt: isoDaysAgo(21),
    updatedAt: isoDaysAgo(0, 9),
    balanceCount: 4,
    positionCount: 1,
    totalValueUsd: 298900,
  },
  {
    id: 3,
    type: "ONCHAIN",
    provider: "EVM",
    name: "Main EVM Wallet",
    publicRef: "0x4e8a...98f2",
    status: "ACTIVE",
    lastSyncedAt: isoDaysAgo(0, 8),
    lastError: null,
    createdAt: isoDaysAgo(14),
    updatedAt: isoDaysAgo(0, 8),
    balanceCount: 6,
    positionCount: 3,
    totalValueUsd: 352410,
  },
  {
    id: 4,
    type: "ONCHAIN",
    provider: "SOLANA",
    name: "Solana Wallet",
    publicRef: "8q5H...pN7x",
    status: "FAILED",
    lastSyncedAt: isoDaysAgo(1, 23),
    lastError: "Rate limited by provider. Retry after cooldown.",
    createdAt: isoDaysAgo(9),
    updatedAt: isoDaysAgo(1, 23),
    balanceCount: 2,
    positionCount: 0,
    totalValueUsd: 64630,
  },
];

export const previewManualAssets: ManualAssetRecord[] = [
  {
    id: 101,
    name: "招商银行活期",
    type: "CASH",
    amount: 520000,
    valueUsd: 72000,
    note: "备用现金",
    createdAt: isoDaysAgo(40),
    updatedAt: isoDaysAgo(2),
  },
  {
    id: 102,
    name: "VOO ETF",
    type: "FUND",
    amount: 180,
    valueUsd: 91800,
    note: "长期指数仓位",
    createdAt: isoDaysAgo(71),
    updatedAt: isoDaysAgo(7),
  },
  {
    id: 103,
    name: "Private Credit",
    type: "OTHER",
    amount: 1,
    valueUsd: 45000,
    note: "按最近估值口径记录",
    createdAt: isoDaysAgo(17),
    updatedAt: isoDaysAgo(4),
  },
];

export const previewAssetBalances: AssetBalanceRecord[] = [
  {
    id: 1,
    sourceId: 1,
    sourceName: "Binance Main",
    sourceType: "CEX",
    assetSymbol: "USDT",
    assetName: "Tether",
    amount: 265000,
    valueUsd: 265000,
    category: "SPOT",
    updatedAt: isoDaysAgo(0, 10),
  },
  {
    id: 2,
    sourceId: 1,
    sourceName: "Binance Main",
    sourceType: "CEX",
    assetSymbol: "FDUSD",
    assetName: "First Digital USD",
    amount: 161250,
    valueUsd: 161250,
    category: "EARN",
    updatedAt: isoDaysAgo(0, 10),
  },
  {
    id: 3,
    sourceId: 2,
    sourceName: "OKX Yield",
    sourceType: "CEX",
    assetSymbol: "USDC",
    assetName: "USD Coin",
    amount: 198900,
    valueUsd: 198900,
    category: "EARN",
    updatedAt: isoDaysAgo(0, 9),
  },
  {
    id: 4,
    sourceId: 2,
    sourceName: "OKX Yield",
    sourceType: "CEX",
    assetSymbol: "BTC",
    assetName: "Bitcoin",
    amount: 0.95,
    valueUsd: 87240,
    category: "SPOT",
    updatedAt: isoDaysAgo(0, 9),
  },
  {
    id: 5,
    sourceId: 3,
    sourceName: "Main EVM Wallet",
    sourceType: "ONCHAIN",
    assetSymbol: "ETH",
    assetName: "Ethereum",
    amount: 38.2,
    valueUsd: 124210,
    category: "SPOT",
    updatedAt: isoDaysAgo(0, 8),
  },
  {
    id: 6,
    sourceId: 3,
    sourceName: "Main EVM Wallet",
    sourceType: "ONCHAIN",
    assetSymbol: "USDe",
    assetName: "Ethena USDe",
    amount: 142000,
    valueUsd: 142000,
    category: "DEFI",
    updatedAt: isoDaysAgo(0, 8),
  },
  {
    id: 7,
    sourceId: 4,
    sourceName: "Solana Wallet",
    sourceType: "ONCHAIN",
    assetSymbol: "SOL",
    assetName: "Solana",
    amount: 410,
    valueUsd: 64630,
    category: "SPOT",
    updatedAt: isoDaysAgo(1, 23),
  },
];

export const previewAssetPositions: AssetPositionRecord[] = [
  {
    id: 1,
    sourceId: 3,
    sourceName: "Main EVM Wallet",
    sourceType: "ONCHAIN",
    provider: "AAVE",
    chain: "Ethereum",
    protocolId: "aave-v3",
    protocolName: "Aave V3",
    positionType: "LENDING",
    assetValueUsd: 76500,
    debtValueUsd: 0,
    rewardValueUsd: 1120,
    netValueUsd: 77620,
    updatedAt: isoDaysAgo(0, 8),
  },
  {
    id: 2,
    sourceId: 3,
    sourceName: "Main EVM Wallet",
    sourceType: "ONCHAIN",
    provider: "Pendle",
    chain: "Ethereum",
    protocolId: "pendle-usde",
    protocolName: "Pendle USDe",
    positionType: "LP",
    assetValueUsd: 89100,
    debtValueUsd: 0,
    rewardValueUsd: 1820,
    netValueUsd: 90920,
    updatedAt: isoDaysAgo(0, 8),
  },
  {
    id: 3,
    sourceId: 2,
    sourceName: "OKX Yield",
    sourceType: "CEX",
    provider: "OKX",
    chain: null,
    protocolId: "okx-simple-earn",
    protocolName: "Simple Earn",
    positionType: "STAKING",
    assetValueUsd: 12100,
    debtValueUsd: 0,
    rewardValueUsd: 280,
    netValueUsd: 12380,
    updatedAt: isoDaysAgo(0, 9),
  },
];

export const previewAssetSnapshots: AssetSnapshotRecord[] = Array.from({ length: 30 }, (_, index) => {
  const daysAgo = 29 - index;
  const base = 1225000;
  const drift = index * 3850;
  const oscillation = ((index % 5) - 2) * 2200;
  return {
    snapshotDate: isoDaysAgo(daysAgo, 7).slice(0, 10),
    totalValueUsd: base + drift + oscillation,
    createdAt: isoDaysAgo(daysAgo, 7),
  };
});

export const previewAssetSyncLogs: AssetSyncLogRecord[] = [
  {
    id: 1,
    userId: 0,
    sourceId: 4,
    sourceName: "Solana Wallet",
    status: "FAILED",
    balanceCount: 2,
    durationMs: 1842,
    errorMessage: "Rate limited by provider. Retry after cooldown.",
    startedAt: isoDaysAgo(1, 23),
    finishedAt: isoDaysAgo(1, 23),
    createdAt: isoDaysAgo(1, 23),
  },
  {
    id: 2,
    userId: 0,
    sourceId: 3,
    sourceName: "Main EVM Wallet",
    status: "SUCCESS",
    balanceCount: 6,
    durationMs: 1260,
    errorMessage: null,
    startedAt: isoDaysAgo(0, 8),
    finishedAt: isoDaysAgo(0, 8),
    createdAt: isoDaysAgo(0, 8),
  },
];

export const previewAssetSummary: AssetSummaryResponse = {
  summary: {
    totalValueUsd: 1279990,
    changeUsd: 21240,
    changePercent: 1.69,
    sourceCount: previewAssetSources.length,
    manualAssetCount: previewManualAssets.length,
    failedSourceCount: previewAssetSources.filter((item) => item.status === "FAILED").length,
    lastSyncedAt: isoDaysAgo(0, 10),
    snapshotDate: new Date().toISOString().slice(0, 10),
  },
  sourceTypeBreakdown: [
    { type: "CEX", valueUsd: 737530, percentage: 57.62 },
    { type: "ONCHAIN", valueUsd: 430570, percentage: 33.64 },
    { type: "MANUAL", valueUsd: 208800, percentage: 16.31 },
  ],
  categoryBreakdown: [
    { category: "SPOT", valueUsd: 541080, percentage: 42.27 },
    { category: "EARN", valueUsd: 360150, percentage: 28.14 },
    { category: "DEFI", valueUsd: 310540, percentage: 24.26 },
    { category: "CASH", valueUsd: 72000, percentage: 5.62 },
  ],
  topAssets: [
    {
      label: "Binance",
      category: "SPOT / EARN",
      sourceType: "CEX",
      sourceId: 1,
      sourceName: "Binance",
      categories: ["SPOT", "EARN"],
      sourceTypes: ["CEX"],
      valueUsd: 426250,
      balanceCount: 2,
      positionCount: 0,
      manualAssetCount: 0,
    },
    {
      label: "Ethereum Wallet",
      category: "DEFI / SPOT",
      sourceType: "ONCHAIN",
      sourceId: 3,
      sourceName: "Ethereum Wallet",
      categories: ["DEFI", "SPOT"],
      sourceTypes: ["ONCHAIN"],
      valueUsd: 430570,
      balanceCount: 2,
      positionCount: 2,
      manualAssetCount: 0,
    },
    {
      label: "Manual",
      category: "FUND / CASH",
      sourceType: "MANUAL",
      sourceId: null,
      sourceName: "Manual",
      categories: ["FUND", "CASH"],
      sourceTypes: ["MANUAL"],
      valueUsd: 208800,
      balanceCount: 0,
      positionCount: 0,
      manualAssetCount: 3,
    },
  ],
  healthSummary: {
    hasIssues: true,
    issueCount: 1,
  },
  meta: {
    generatedAt: new Date().toISOString(),
  },
};
